apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapplje
  name: myapplje
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapplje
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapplje
    spec:
      containers:
      - image: jeaeun708/bus:pj
        imagePullPolicy: IfNotPresent
        name: bus
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapplje
  name: myapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: myapplje
  type: NodePort
status:
  loadBalancer: {}

